### PR TITLE
Include `object/` in the package

### LINKED ISSUE #60: Broken publish?
Seems like `trine/object/…` functions aren’t in the package:

```
Module not found: Error: Cannot resolve module 'trine/object/values'
```

See https://registry.npmjs.org/trine/-/trine-0.1.0.tgz – there’s no `object` folder there.

### PR DESCRIPTION
**Pull request by tomekwi**
Fixes #60

### CODE REVIEW

**Comment by tomekwi** [comment]
By the way, if you want to make the files entry more explicit, you can prefix each item with / (only take the file it it’s in the project’s root) and suffix it with / (only take the file if it’s a directory).

**Comment by jussi-kalliokoski** [comment]
Oops!!! Maybe I should automate this to keep me from doing the same mistake again. :laughing:

Thanks! :heart: :tada:

> By the way, if you want to make the files entry more explicit, you can prefix each item with / (only take the file it it’s in the project’s root) and suffix it with / (only take the file if it’s a directory).

Oh cool, thanks! That sounds like a good idea.

**Comment by tomekwi** [comment]
Hi, thanks for merging!

Could you please publish a patch? Right now I have to depend on https://github.com/tomekwi/trine/tree/edge – which is quite hacky :)

**Comment by jussi-kalliokoski** [comment]
Published 0.2.1 :)

**Comment by tomekwi** [comment]
:+1: :+1:

**Pull request merged**
