### PR TITLE
Add iterable-some to the hall of fame

### PR DESCRIPTION
**Pull request by tomekwi**
Thanks for the section in the readme @jussi-kalliokoski!

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
Eep, sorry for the wait on this one as well. :/ I'll merge this when #67 is finished so that it'll build cleanly. :)

**Comment by tomekwi** [comment]
Got another one here :)

https://github.com/studio-b12/this-drop

**Comment by tomekwi** [comment]
And take it easy @jussi-kalliokoski :)

It’s not burning, as we say in Poland.

**Comment by tomekwi** [comment]
Closing to remove clutter 🙂

Feel free to open if you think this is mergeable.

**Comment by jussi-kalliokoski** [comment]
It appears I have the attention span of a goldfish 😜

**Pull request merged**
